/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* I2C_SCL */
#define I2C_SCL_0_DRIVEMODE CY_GPIO_DM_PULLUP
#define I2C_SCL_0_INBUF_ENABLED 1u
#define I2C_SCL_0_INIT_DRIVESTATE 1u
#define I2C_SCL_0_INIT_MUXSEL 19u
#define I2C_SCL_0_INPUT_SYNC 2u
#define I2C_SCL_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define I2C_SCL_0_NUM 4u
#define I2C_SCL_0_PORT GPIO_PRT6
#define I2C_SCL_0_SLEWRATE CY_GPIO_SLEW_FAST
#define I2C_SCL_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define I2C_SCL_DRIVEMODE CY_GPIO_DM_PULLUP
#define I2C_SCL_INBUF_ENABLED 1u
#define I2C_SCL_INIT_DRIVESTATE 1u
#define I2C_SCL_INIT_MUXSEL 19u
#define I2C_SCL_INPUT_SYNC 2u
#define I2C_SCL_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define I2C_SCL_NUM 4u
#define I2C_SCL_PORT GPIO_PRT6
#define I2C_SCL_SLEWRATE CY_GPIO_SLEW_FAST
#define I2C_SCL_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* I2C_SDA */
#define I2C_SDA_0_DRIVEMODE CY_GPIO_DM_PULLUP
#define I2C_SDA_0_INBUF_ENABLED 1u
#define I2C_SDA_0_INIT_DRIVESTATE 1u
#define I2C_SDA_0_INIT_MUXSEL 19u
#define I2C_SDA_0_INPUT_SYNC 2u
#define I2C_SDA_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define I2C_SDA_0_NUM 5u
#define I2C_SDA_0_PORT GPIO_PRT6
#define I2C_SDA_0_SLEWRATE CY_GPIO_SLEW_FAST
#define I2C_SDA_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define I2C_SDA_DRIVEMODE CY_GPIO_DM_PULLUP
#define I2C_SDA_INBUF_ENABLED 1u
#define I2C_SDA_INIT_DRIVESTATE 1u
#define I2C_SDA_INIT_MUXSEL 19u
#define I2C_SDA_INPUT_SYNC 2u
#define I2C_SDA_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define I2C_SDA_NUM 5u
#define I2C_SDA_PORT GPIO_PRT6
#define I2C_SDA_SLEWRATE CY_GPIO_SLEW_FAST
#define I2C_SDA_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_rx */
#define UART_rx_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_rx_0_INBUF_ENABLED 1u
#define UART_rx_0_INIT_DRIVESTATE 1u
#define UART_rx_0_INIT_MUXSEL 18u
#define UART_rx_0_INPUT_SYNC 2u
#define UART_rx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_rx_0_NUM 0u
#define UART_rx_0_PORT GPIO_PRT5
#define UART_rx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_rx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_rx_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_rx_INBUF_ENABLED 1u
#define UART_rx_INIT_DRIVESTATE 1u
#define UART_rx_INIT_MUXSEL 18u
#define UART_rx_INPUT_SYNC 2u
#define UART_rx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_rx_NUM 0u
#define UART_rx_PORT GPIO_PRT5
#define UART_rx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_rx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_tx */
#define UART_tx_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_tx_0_INBUF_ENABLED 0u
#define UART_tx_0_INIT_DRIVESTATE 1u
#define UART_tx_0_INIT_MUXSEL 18u
#define UART_tx_0_INPUT_SYNC 2u
#define UART_tx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_tx_0_NUM 1u
#define UART_tx_0_PORT GPIO_PRT5
#define UART_tx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_tx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_tx_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_tx_INBUF_ENABLED 0u
#define UART_tx_INIT_DRIVESTATE 1u
#define UART_tx_INIT_MUXSEL 18u
#define UART_tx_INPUT_SYNC 2u
#define UART_tx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_tx_NUM 1u
#define UART_tx_PORT GPIO_PRT5
#define UART_tx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_tx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
